import { ShieldCheck, UserCog } from "lucide-react";
import { notFound } from "next/navigation";
import { listBranches, listUsersAndRoles } from "@/db/queries";
import { getCurrentUser } from "@/lib/auth";
import { canManageRoles } from "@/lib/authorization";
import { statusLabel } from "@/lib/format";

export default async function AccessPage({ searchParams }: { searchParams: Promise<{ success?: string; error?: string }> }) {
  const actor = (await getCurrentUser())!;
  if (!canManageRoles(actor)) notFound();
  const [{ users, assignments, roles }, branches, state] = await Promise.all([listUsersAndRoles(), listBranches(), searchParams]);
  return <main className="dashboard-content"><div className="dash-page-heading"><div><p>Серверлік авторизация</p><h1>Рөлдер мен құқықтар</h1></div><span className="immutable-pill"><ShieldCheck size={15} /> A деңгейі</span></div>{state.success && <div className="dash-alert success">Рөл өзгертілді және аудитке тіркелді.</div>}{state.error && <div className="dash-alert error">Рөлді өзгерту мүмкін болмады. Аумақ пен құқықтарды тексеріңіз.</div>}<section className="access-overview"><div><span>A</span><strong>Толық</strong><small>Президент, I вице-президент</small></div><div><span>B</span><strong>Департамент</strong><small>Тек кәсіби міндет деректері</small></div><div><span>C</span><strong>Филиал</strong><small>Тек өз өңірі</small></div><div><span>D</span><strong>Мүше</strong><small>Тек өз профилі</small></div></section><div className="access-grid"><section className="panel"><div className="panel-heading"><div><span>Тағайындау</span><h2>Жаңа рөл беру</h2></div><UserCog size={20} /></div><form className="role-form" action="/api/access/roles" method="post"><input type="hidden" name="action" value="grant" /><label>Пайдаланушы<select name="userId" required>{users.map((user) => <option value={user.id} key={user.id}>{user.fullName} · {user.email}</option>)}</select></label><label>Рөл<select name="roleId" required>{roles.map((role) => <option value={role.id} key={role.id}>{role.accessLevel} · {role.nameKk}</option>)}</select></label><label>Аумақ идентификаторы<select name="scopeId" defaultValue=""><option value="">Жаһандық немесе қолданылмайды</option>{branches.map((branch) => <option key={branch.id} value={branch.id}>{branch.regionName}</option>)}<option value="dept-content">Математика және мазмұн департаменті</option></select></label><button className="button button-secondary" type="submit">Рөл беру</button></form></section><section className="panel wide"><div className="panel-heading"><div><span>Белсенді құқықтар</span><h2>Пайдаланушылар</h2></div><span>{assignments.length} тағайындау</span></div><div className="assignment-list">{users.map((user) => { const userAssignments = assignments.filter((assignment) => assignment.userId === user.id); return <article key={user.id}><div><strong>{user.fullName}</strong><small>{user.email} · {statusLabel(user.membershipStatus)}</small></div><div className="role-chips">{userAssignments.length ? userAssignments.map((assignment) => <form key={assignment.id} action="/api/access/roles" method="post"><input type="hidden" name="action" value="revoke" /><input type="hidden" name="assignmentId" value={assignment.id} /><button title="Рөлді қайтару" type="submit">{assignment.nameKk}<span>×</span></button></form>) : <span className="no-role">Жүйелік рөл жоқ</span>}</div></article>; })}</div></section></div></main>;
}
