import { Eye, EyeOff, PencilLine, ShieldCheck } from "lucide-react";
import { StatusBadge } from "@/app/components/StatusBadge";
import { getOwnProfile } from "@/db/queries";
import { getCurrentUser } from "@/lib/auth";
import { formatDate } from "@/lib/format";

export default async function ProfilePage({ searchParams }: { searchParams: Promise<{ success?: string; error?: string }> }) {
  const user = (await getCurrentUser())!;
  const [profile, state] = await Promise.all([getOwnProfile(user), searchParams]);
  if (!profile) return null;
  return <main className="dashboard-content"><div className="dash-page-heading"><div><p>Бір адам · бір профиль</p><h1>Менің профилім</h1></div><StatusBadge status={user.membershipStatus} /></div>{state.success && <div className="dash-alert success">Профиль жаңартылды. Өзгеріс аудит журналында сақталды.</div>}{state.error && <div className="dash-alert error">Деректерді жаңарту мүмкін болмады.</div>}<div className="profile-layout"><section className="panel"><div className="panel-heading"><div><span><PencilLine size={15} /> 1-қабат</span><h2>Өзгертуге болатын деректер</h2></div><span className="visibility-label"><Eye size={15} /> Сізге көрінеді</span></div><form className="profile-form" action="/api/profile" method="post"><div className="form-grid"><label>Телефон<input name="phone" required defaultValue={String(profile.phone ?? "")} /></label><label>Email<input name="email" type="email" required defaultValue={String(profile.email ?? "")} /></label><label>Жұмыс орны<input name="workplace" defaultValue={String(profile.workplace ?? "")} /></label><label>Лауазымы<input name="position" defaultValue={String(profile.position ?? "")} /></label><label className="span-2">Кәсіби тәжірибе<textarea name="professionalExperience" rows={3} defaultValue={String(profile.professional_experience ?? "")} /></label><label className="span-2">Математикалық мамандану<textarea name="mathSpecialization" rows={2} defaultValue={String(profile.math_specialization ?? "")} /></label><label className="span-2">Кәсіби жетістіктер<textarea name="achievements" rows={3} defaultValue={String(profile.achievements ?? "")} /></label><label className="span-2">Кәсіби өмірбаян<textarea name="biography" rows={4} defaultValue={String(profile.biography ?? "")} /></label></div><button className="button button-primary" type="submit">Өзгерістерді сақтау</button></form></section><aside><section className="profile-official"><div><ShieldCheck size={21} /><span>2-қабат</span></div><h2>Ресми деректер</h2><p>Бұл ақпарат сізге көрінеді, бірақ тек уәкілетті әкімшілік арқылы өзгереді.</p><dl><div><dt>Мүшелік мәртебесі</dt><dd><StatusBadge status={String(profile.membership_status)} /></dd></div><div><dt>Мүшелік басталған күн</dt><dd>{formatDate(String(profile.membership_started_at ?? ""))}</dd></div><div><dt>Филиал</dt><dd>{String(profile.branchName ?? "—")}</dd></div><div><dt>Туған жыл</dt><dd>{String(profile.birth_year ?? "—")}</dd></div></dl></section><section className="profile-internal"><EyeOff size={21} /><div><span>3-қабат</span><h2>Ішкі деректер қорғалған</h2><p>Қызметтік жазбалар, әкімшілік бағалар және аудит ақпараты мүше профилінде көрсетілмейді.</p></div></section></aside></div></main>;
}
