/* eslint-disable @next/next/no-html-link-for-pages -- vinext dashboard transitions require native navigation. */
import { ArrowLeft, Download, ExternalLink, FileText, Milestone, Users } from "lucide-react";
import { notFound } from "next/navigation";
import { ProjectForm } from "@/app/components/ProjectForm";
import { ProjectStageBatchForm } from "@/app/components/ProjectStageBatchForm";
import { getManagedProject, getProjectFormOptions, listEligibleProjectMembers } from "@/db/projects";
import { getCurrentUser } from "@/lib/auth";
import {
  canAccessManagedProject, canManageGlobalProjects, canManageProjectDocuments, canManageProjectParticipants,
  canManageProjectResults, canManageProjectStages,
} from "@/lib/authorization";
import { formatDate } from "@/lib/format";
import {
  allowedProjectTransitions, projectDocumentCategories, projectDocumentCategoryLabel, projectParticipantRoleLabel,
  projectCoverageLabel, projectParticipantRoles, projectParticipantStatusLabel, projectScopeLabel, projectStageStatusLabel, projectStageStatuses, projectStatusLabel,
} from "@/lib/projects";

function message(state: { success?: string; error?: string }) {
  if (state.success) return { kind: "success", text: "Өзгеріс сақталып, аудит журналына тіркелді." };
  if (state.error === "duplicate") return { kind: "error", text: "Бұл адам жобаға бұрын қосылған." };
  if (state.error === "leader") return { kind: "error", text: "Жетекшіні шығару үшін алдымен жоба дерегіндегі жетекшіні ауыстырыңыз." };
  if (state.error) return { kind: "error", text: "Өзгеріс сақталмады. Енгізілген деректі және рұқсат аумағын тексеріңіз." };
  return null;
}

export default async function DashboardProjectDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ success?: string; error?: string }> }) {
  const actor = (await getCurrentUser())!;
  const { id } = await params;
  const [project, state] = await Promise.all([getManagedProject(id), searchParams]);
  if (!project || !canAccessManagedProject(actor, project)) notFound();
  const [options, members] = await Promise.all([getProjectFormOptions(actor), listEligibleProjectMembers(actor, project)]);
  const note = message(state);
  const activeParticipants = project.participants.filter((participant) => participant.status === "ACTIVE").length;
  const completedParticipants = project.participants.filter((participant) => participant.status === "COMPLETED").length;
  const completedStages = project.stages.filter((stage) => stage.status === "COMPLETED").length;
  const archived = project.status === "ARCHIVED";
  return <main className="dashboard-content">
    <a className="back-link" href="/dashboard/projects"><ArrowLeft size={15} /> Жобалар</a>
    <div className="dash-page-heading"><div><p>{project.code ?? projectScopeLabel(project.projectScope)}</p><h1>{project.title}</h1></div><span className={`project-status large ${project.status.toLowerCase()}`}>{projectStatusLabel(project.status)}</span></div>
    {note && <div className={`dash-alert ${note.kind}`}>{note.text}</div>}
    <section className="project-overview-grid"><article><span>Мерзімі</span><strong>{formatDate(project.startDate.toISOString())}</strong><small>{project.endDate ? formatDate(project.endDate.toISOString()) : "Мерзімсіз"}</small></article><article><span>Жетекші</span><strong>{project.leaderProfile?.fullName ?? "Тағайындалмаған"}</strong><small>{projectCoverageLabel(project)}</small></article><article><span>Қатысушылар</span><strong>{activeParticipants} белсенді</strong><small>{completedParticipants} адамның тарихына түсті</small></article><article><span>Кезеңдер</span><strong>{completedStages} / {project.stages.length}</strong><small>аяқталған</small></article></section>
    {project.publicProject && <a className="project-public-link" href={`/projects/${project.publicProject.slug}`} target="_blank" rel="noreferrer"><ExternalLink size={16} /> Ашық сайттағы «{project.publicProject.title}» жазбасын көру · {project.publicProject.status}</a>}

    {!archived && <details className="panel project-edit-panel"><summary>Негізгі деректерді өңдеу</summary><ProjectForm action={`/api/projects/${id}`} options={options} canChooseNational={canManageGlobalProjects(actor) || project.projectScope === "NATIONAL"} canChooseAllBranches={canManageGlobalProjects(actor)} item={project} submitLabel="Өзгерісті сақтау" /></details>}
    <section className="panel project-workflow"><div><span>Жоба мәртебесі</span><h2>{projectStatusLabel(project.status)}</h2><p>{project.statusNote ?? "Мәртебе бойынша түсініктеме жоқ."}</p></div><div>{allowedProjectTransitions(project.status).map((status) => <form action={`/api/projects/${id}`} method="post" key={status}><input name="action" type="hidden" value="status" /><input name="status" type="hidden" value={status} /><input maxLength={2000} name="reason" placeholder="Түсініктеме" required={status === "CANCELLED" || status === "ARCHIVED"} /><button className={status === "CANCELLED" || status === "ARCHIVED" ? "button button-danger" : "button"} type="submit">{projectStatusLabel(status)}</button></form>)}</div></section>

    <section className="panel project-section" id="project-stages"><div className="panel-heading"><div><span>Жұмыс жоспары</span><h2><Milestone size={18} /> Кезеңдер</h2></div><strong>{completedStages}/{project.stages.length}</strong></div>{!archived && canManageProjectStages(actor, project) && <ProjectStageBatchForm projectId={id} />}<div className="project-stage-list">{project.stages.map((stage, index) => <article key={stage.id}><span className="stage-number">{index + 1}</span><div><strong>{stage.title}</strong><p>{stage.description ?? "Сипаттама жоқ"}</p><small>{stage.startDate ? formatDate(stage.startDate.toISOString()) : "Басталу күні жоқ"} — {stage.endDate ? formatDate(stage.endDate.toISOString()) : "аяқталу күні жоқ"}</small></div><span className={`stage-status ${stage.status.toLowerCase()}`}>{projectStageStatusLabel(stage.status)}</span>{!archived && canManageProjectStages(actor, project) && <details><summary>Басқару</summary><form action={`/api/projects/${id}/stages`} method="post"><input name="action" type="hidden" value="status" /><input name="stageId" type="hidden" value={stage.id} /><select defaultValue={stage.status} name="status">{projectStageStatuses.map((status) => <option key={status} value={status}>{projectStageStatusLabel(status)}</option>)}</select><button className="button" type="submit">Мәртебені сақтау</button></form><form action={`/api/projects/${id}/stages`} method="post"><input name="action" type="hidden" value="update" /><input name="stageId" type="hidden" value={stage.id} /><input defaultValue={stage.title} maxLength={240} name="title" required /><input defaultValue={stage.startDate?.toISOString().slice(0, 10) ?? ""} name="startDate" type="date" /><input defaultValue={stage.endDate?.toISOString().slice(0, 10) ?? ""} name="endDate" type="date" /><textarea defaultValue={stage.description ?? ""} maxLength={2000} name="description" /><button className="button" type="submit">Деректі сақтау</button></form></details>}</article>)}{project.stages.length === 0 && <p className="empty-content">Жоба кезеңдері әлі қосылмаған.</p>}</div></section>

    <section className="panel project-section" id="project-participants"><div className="panel-heading"><div><span>Команда</span><h2><Users size={18} /> Қатысушылар</h2></div><strong>{project.participants.length}</strong></div>{!archived && canManageProjectParticipants(actor, project) && <form action={`/api/projects/${id}/participants`} className="project-participant-add" method="post"><input name="action" type="hidden" value="add" /><select name="personId" required defaultValue=""><option disabled value="">Мүшені таңдаңыз</option>{members.map((member) => <option key={member.id} value={member.id}>{member.fullName}{member.branch ? ` · ${member.branch.regionName}` : ""}</option>)}</select><select defaultValue="PARTICIPANT" name="participantRole">{projectParticipantRoles.map((role) => <option key={role} value={role}>{projectParticipantRoleLabel(role)}</option>)}</select><button className="button button-primary" type="submit">Командаға қосу</button></form>}<div className="project-participant-list">{project.participants.map((participant) => <article key={participant.id}><a href={`/dashboard/members/${participant.person.id}`}><strong>{participant.person.fullName}</strong><small>{participant.person.position ?? participant.person.workplace ?? participant.person.email}</small></a><span>{projectParticipantRoleLabel(participant.participantRole)}</span><i className={participant.status.toLowerCase()}>{projectParticipantStatusLabel(participant.status)}</i>{!archived && canManageProjectParticipants(actor, project) && <details><summary>Өзгерту</summary><form action={`/api/projects/${id}/participants`} method="post"><input name="action" type="hidden" value="update" /><input name="participantId" type="hidden" value={participant.id} /><select defaultValue={participant.participantRole} name="participantRole">{projectParticipantRoles.map((role) => <option key={role} value={role}>{projectParticipantRoleLabel(role)}</option>)}</select><select defaultValue={participant.status} name="status"><option value="ACTIVE">Қатысып жүр</option><option value="COMPLETED">Қатысты</option><option value="WITHDRAWN">Шыққан</option></select><input defaultValue={participant.notes ?? ""} maxLength={2000} name="notes" placeholder="Ескерту" /><button className="button" type="submit">Сақтау</button></form></details>}</article>)}</div></section>

    <div className="project-bottom-grid">
      <section className="panel project-section" id="project-documents"><div className="panel-heading"><div><span>Жеке сақтау</span><h2><FileText size={18} /> Құжаттар</h2></div><strong>{project.documents.length}</strong></div>{!archived && canManageProjectDocuments(actor, project) && <form action={`/api/projects/${id}/documents`} className="project-document-upload" encType="multipart/form-data" method="post"><select name="category">{projectDocumentCategories.map((category) => <option key={category} value={category}>{projectDocumentCategoryLabel(category)}</option>)}</select><input accept=".pdf,.jpg,.jpeg,.png,.docx,.xlsx,.pptx" name="document" required type="file" /><button className="button button-primary" type="submit">Жүктеу</button></form>}<div className="project-document-list">{project.documents.map((document) => <article key={document.id}><span><FileText size={16} /></span><div><strong>{document.originalName}</strong><small>{projectDocumentCategoryLabel(document.category)} · {Math.ceil(document.sizeBytes / 1024)} КБ</small></div><a href={`/api/projects/${id}/documents/${document.id}`}><Download size={14} /> Алу</a>{!archived && canManageProjectDocuments(actor, project) && <form action={`/api/projects/${id}/documents/${document.id}`} method="post"><button className="button button-danger" type="submit">Архив</button></form>}</article>)}{project.documents.length === 0 && <p className="empty-content">Жоба құжаты жоқ.</p>}</div></section>
      <section className="panel project-section" id="project-result"><div className="panel-heading"><div><span>Қорытынды</span><h2>Жоба нәтижесі</h2></div></div>{canManageProjectResults(actor, project) && !archived ? <form action={`/api/projects/${id}/result`} className="project-result-form" method="post"><label><span>Қысқаша қорытынды *</span><textarea defaultValue={project.result?.summary ?? ""} maxLength={10000} name="summary" required rows={4} /></label><label><span>Негізгі нәтижелер</span><textarea defaultValue={project.result?.outcomes ?? ""} maxLength={20000} name="outcomes" rows={4} /></label><label><span>Дайын өнімдер / материалдар</span><textarea defaultValue={project.result?.deliverables ?? ""} maxLength={20000} name="deliverables" rows={3} /></label><div><label><span>Қамтылған адам саны</span><input defaultValue={project.result?.beneficiaryCount ?? ""} min={0} name="beneficiaryCount" type="number" /></label><label><span>Нақты аяқталған күні</span><input defaultValue={project.result?.completedAt?.toISOString().slice(0, 10) ?? ""} name="completedAt" type="date" /></label></div><button className="button button-primary" type="submit">Нәтижені сақтау</button></form> : <div className="project-result-read"><strong>{project.result?.summary ?? "Нәтиже әлі толтырылмаған"}</strong>{project.result?.outcomes && <p>{project.result.outcomes}</p>}</div>}</section>
    </div>
  </main>;
}
